# -*- coding: utf-8 -*-
"""project deep

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ls4Mdz4B38px1JcQoT070NePPvS5RHYT
"""

# %matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

print("my big b VIkash")

